insert into Product values(2, ' Double Chocolate Chip Cookie', 1.00);
insert into Product values(3, 'Oatmeal Raisin Cookie', 1.00);
insert into Product values(9, 'Sugar Cookie', 1.00);
insert into Product values(10, 'Maple Cookie', 1.00);
insert into Product values(11, 'Banana Bread Loaf', 5.50);
insert into Product values(12, 'Chocolate Chip Loaf', 5.50);
insert into Product values(13, 'Double Chocolate Chip Loaf', 6.00);
insert into Product values(14, 'Lemon Poppyseed Loaf', 5.50);
insert into Product values(15, 'Apple Pie', 10.00);
insert into Product values(16, 'Apple Crisp', 9.00);
insert into Product values(17, 'Peach Pie', 10.00);
insert into Product values(18, 'Pecan Pie', 12.00);
insert into Product values(19, 'Blueberry Pie', 10.00);
insert into Product values(20, 'Cherry Pie', 10.00);
insert into Product values(21, 'Lemon Meringue Pie', 12.00);
insert into Product values(22, 'Strawberry Rhubarb Pie', 10.00);
insert into Product values(23, 'Vanilla Ice Cream Cone', 2.50);
insert into Product values(24, 'Chocolate Ice Cream Cone', 2.50);
insert into Product values(25, 'Vanilla Ice Cream Sandwich', 4.50);
insert into Product values(26, 'Chocolate Ice Cream Sandwich', 4.50);
insert into Product values(27, 'Butter Tart', 3.00);
insert into Product values(28, 'Pecan Butter Tart', 3.00);
insert into Product values(29, 'Raisin Butter Tart', 3.00);
insert into Product values(30, 'Strawberry Cheesecake', 14.00);
insert into Product values(31, 'Blueberry Cheesecake', 14.00);
insert into Product values(32, 'Apple Cinnamon Cheesecake', 14.00);
insert into Product values(33, 'Maple Brown Sugar Cheesecake', 15.00);
insert into Product values(34, 'Chocolate Cheesecake', 14.00);
insert into Product values(35, 'Vanilla Cheesecake', 14.00);
insert into Product values(36, 'Oreo Cheesecake', 15.00);
insert into Product values(37, 'Strawberry Cake', 18.50);
insert into Product values(38, 'Blueberry Cake', 18.50);
insert into Product values(39, 'Apple Cinnamon Cake', 18.50);
insert into Product values(40, 'Coffee Cake', 18.50);
insert into Product values(41, 'Double Chocolate Cake', 20.00);
insert into Product values(42, 'Vanilla Cake', 18.50);
insert into Product values(43, 'Lemon Cake', 18.50);
insert into Product values(44, 'Vanilla Ice Cream Cake', 23.00);
insert into Product values(45, 'Chocolate Ice Cream Cake', 23.00);
insert into Product values(46, 'Oreo Ice Cream Cake', 25.00);
insert into Product values(47, 'Vanilla Cupcake', 3.00);
insert into Product values(48, 'Chocolate Cupcake', 3.00);
insert into Product values(49, 'Caramel Coffee Cupcake', 3.50);
insert into Product values(50, 'Red Velvet Cupcake', 3.50);
insert into Product values(1, 'Cinnamon Roll', 4.00);
insert into Product values(4, 'Maple Brown Sugar Coffee Loaf', 5.50);
insert into Product values(8, 'Pumpkin Pie', 10.00);

